/*
 * nvenc_grc_hdrs.h - GENERATED by tools/nvenc_replay.py gen. Do not edit.
 *
 * Annex-B SPS + PPS for the stream NVENC writes with grc's setup
 * (logs/m79-runE-setups/setup_8.bin): NVENC emits slices only, and grc writes
 * its own parameter sets. The VUI says BT.709 limited range (the VIC's M83
 * matrix), 60 fps, and no frame reordering. The console puts these in front
 * of every IDR frame it streams, so the stream decodes from any frame and can
 * be fed straight to a stock decoder.
 */
#pragma once

namespace ams::mitm::applet::nvenc_grc_hdrs {

    constexpr u8 SpsPps[41] = {
        0x00, 0x00, 0x00, 0x01, 0x67, 0x64, 0x00, 0x20, 0xac, 0x2b, 0x40, 0x28, 0x02, 0xdd, 0x80, 0xb5,
        0x01, 0x01, 0x01, 0x40, 0x00, 0x00, 0x03, 0x00, 0x40, 0x00, 0x00, 0x1e, 0x03, 0xc2, 0x21, 0x1a,
        0x80, 0x00, 0x00, 0x00, 0x01, 0x68, 0xee, 0x3c, 0xb0,
    };

}
