/*
 * vic_csc_bt709.h - GENERATED by tools/vic_csc.py gen. Do not edit.
 *
 * RGB -> BT.709 limited-range YCbCr for the VIC's output matrix, in the
 * encoding M82 Run H measured (see tools/vic_csc.py for the law and the
 * check): rows (Y, Cr, Cb), columns (B, G, R, offset) for a source declared
 * A8R8G8B8 whose bytes are R,G,B,A; matrix_r_shift 8, so 16 fraction
 * bits (65536 = 1.0); offsets in 1/256 of a 10-bit step, +512 so the output
 * rounds.
 */
#pragma once

namespace ams::mitm::applet::vic_csc {

    constexpr u32 Shift = 8;
    constexpr s32 Bt709[3][4] = {
        {    4064,   40254,   11966,   16896 },
        {   -2639,  -26145,   28784,  131584 },
        {   28785,  -22189,   -6596,  131584 },
    };

}
